### ISSUE TITLE
glare doesnt work properly on border-radius elements

### ISSUE THREAD

**Issue by Rosux** [micku7zu/vanilla-tilt.js#112]
"border-radius:inherit;" fixes this (dunno how to make proper pull request)
but this is how it should be i suppose:
`{position:"absolute",top:"0",left:"0",width:"100%",height:"100%",overflow:"hidden","pointer-events":"none","border-radius":"inherit"}`

**Comment by micku7zu** [comment]
Thanks for the pull request fix. I merged it and I will release the new version with the fix!
