### ISSUE TITLE
Parallax Effect not working on Firefox

### ISSUE THREAD

**Issue by AlexNewson** [micku7zu/vanilla-tilt.js#13]
The parallax effect doesn't appear to work on Firefox (version 51.0.1 (64-bit)) but still works on other browsers. Is this a problem with my website or vanilla-tilt.js?

Site: [https://newsoncreative.co.uk](https://newsoncreative.co.uk)

**Comment by bastilimbach** [comment]
@AlexNewson Please check your markdown. The link is wrong. Should be: `[ link name ]( url )`. Also the subdomain [www.](https://www.newsoncreative.co.uk) returns a 404 error. You should probably redirect this subdomain to [https://newsoncreative.co.uk](https://newsoncreative.co.uk)

**Comment by bastilimbach** [comment]
Btw. The parallax effect doesn't work in firefox for me. 
@micku7zu Maybe a missing css prefix?

**Comment by AlexNewson** [comment]
Thanks, @bastilimbach I was in the process of changing over my www. subdomain as you posted the comment, all fixed now 👍

**Comment by AlexNewson** [comment]
@micku7zu That's done the trick, thanks 😄

**Comment by micku7zu** [comment]
I'm glad that it worked 😄
