### ISSUE TITLE
Looks like does not work on WIX

### ISSUE THREAD

**Issue by renanmalato** [micku7zu/vanilla-tilt.js#133]
Hello, I inserted the script in the Settings / Custom Code page at the end of the Body

I called the class in a div

I inspect the page, made sure that the code was in the Body, but seems to not work the hover effects

Someone have experience to insert that on a Wix platform?

![Screen Shot 2023-12-31 at 3 15 42 PM](https://github.com/micku7zu/vanilla-tilt.js/assets/3617070/f7899949-f773-4ded-a68b-e3b769bdb7f7)

![2Screen Shot 2023-12-31 at 3 16 26 PM copy](https://github.com/micku7zu/vanilla-tilt.js/assets/3617070/a4a85b02-a853-4418-af0e-61c0ef2e1dda)

![Screen Shot 2023-12-31 at 3 16 38 PM](https://github.com/micku7zu/vanilla-tilt.js/assets/3617070/0c34d26a-0be7-4440-9eb4-f3abb77be6a0)

I also tried to install the script by the NPM platform but in some way I cannot call the effect on a div

![Screen Shot 2023-12-31 at 3 21 01 PM](https://github.com/micku7zu/vanilla-tilt.js/assets/3617070/bcc068b9-475f-4241-916d-c7eaf17ba9ec)

**Comment by micku7zu** [comment]
It doesn't matter where you add it, it should work everywhere. 

It depends how your elements are created in the page. If the elements are not present when the VanillaTilt.init function runs, then it won't initiated the script on those elements.

It is not enough to have the script at the end of the body, if the elements are not inside the body when the script is run.

Debugging through screenshots is not enough. Leave a URL and I might be able to help you.

**Comment by renanmalato** [comment]
Hey Mick, Thank you so much for your response. Happy New Year


Here is my test page
https://renan-stnl-uxdesign.com

**There is a black box over a section, this container should be on Vanilla** - at least on my last website not on wix I was able to do that

I appreciate any kind of advice you might have to me

**Comment by micku7zu** [comment]
Ok, at a quick look on this page, there are multiple issues:

1. The vanilla-tilt.js file is not loading correctly. The link you use it is not working as you expect, and it loads as 0bytes. So the library is not loaded. Change the github URL to some CDN. I don't know WIX, I never used WIX, so I don't know what methods you have to load a JS file, but the way you use it right now, it doesn't work. 
[Screenshot](https://github.com/micku7zu/vanilla-tilt.js/assets/3103859/6c71ff26-c490-41e5-ab19-706a88b203dc)
2. The JS code is at the beginning of <body>, so if `VanillaTilt.init` executes at the beginning of <body> when the elements are not on the page, it will not find any elements on the page and it will not apply the effect. You have to include this script at the end of the page, or to run it somehow AFTER the elements are on the page.
3. `.cardglass, .creditcardglass` - your element on the page doesn't have this classes. They are prefixed with `wixui-` 
[Screenshot](https://github.com/micku7zu/vanilla-tilt.js/assets/3103859/7cb7a4ce-52e8-44e7-88f8-796a51a49b98)


If you fix this issues, the effect will work:  [Working effect](https://github.com/micku7zu/vanilla-tilt.js/assets/3103859/871ba791-ec7f-4ff5-b812-b6cd4d592d99) (this was done in developer console, so it is not actually helping you fix the issues above)

**Comment by renanmalato** [comment]
Hi, I fixed the file KBs linking the script to a CDN as you can see in the Network console

and I also inserted the extended class call to the JS `wixui-creditcardglass`

if you have a moment to look the link one more time to see if I missed something I appreciate it, thank you 

<img width="1174" alt="Screen Shot 2024-01-01 at 11 45 36 AM" src="https://github.com/micku7zu/vanilla-tilt.js/assets/3617070/e31e400f-f3db-471a-af95-edf8a2b3e1b9">



<img width="804" alt="Screen Shot 2024-01-01 at 11 44 24 AM" src="https://github.com/micku7zu/vanilla-tilt.js/assets/3617070/f2c2f998-ac8b-4254-b15c-329f24f83806">

**Comment by micku7zu** [comment]
The `<script>` is still loaded at the start of the page, before the elements are inserted on the page. You have to include it at the end. 

Or you can try this code:
```
document.addEventListener("DOMContentLoaded", function(event) {
  VanillaTilt.init(document.querySelectorAll(".cardglass, .creditcardglass, .wixui-creditcardglass"), {
    max: 25,
    speed: 400,
    glare: true,
    "max-glare": 1,
  });
});
```

**Comment by micku7zu** [comment]
I will close the issue as this is not related to the library. The library works, you have to include it correctly.

**Comment by renanmalato** [comment]
Still does not works :(

$100 usd would you help me to include it correctly?



Best regards,



___________________________________________________









RENAN MALATO

UX DESIGNER & MULTIMEDIA

SPECIALIST


DESIGN.RENANMALATO.COM

**Comment by micku7zu** [comment]
Hi,

Send me a meeting link, discord or something and I can help you.

**Comment by renanmalato** [comment]
Meeting link: https://meet.google.com/mtx-rkda-cyq

I will give you a team viewer ID on the chat

**Comment by renanmalato** [comment]
Thank you so much for your hack man, Let me know if you received the
PayPal... not sure if it completed

**Comment by renanmalato** [comment]
I believe now it went,
should be available tomorrow
let me know if all good

email: malatows@gmail.com

![Screen Shot 2024-01-01 at 2 30 46 PM](https://github.com/micku7zu/vanilla-tilt.js/assets/3617070/d44bd1de-fb89-49db-9952-19bb3f3b219f)

**Comment by micku7zu** [comment]
Thanks! I've got them. First donation/money related to vanilla-tilt.js in 8 years, after 3.7k Github stars and 2m downloads on NPM.
