### ISSUE TITLE
Typescript Typings

### ISSUE THREAD

**Issue by BrunnerLivio** [micku7zu/vanilla-tilt.js#14]
A nice-to-have would be some TypeScript Typings by contributing to the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repository. So you have nice support, when you're using TypeScript. 

Are you planning to do this?

**Comment by micku7zu** [comment]
Really sorry, but I'm not really a TypeScript fan. I didn't use TypeScript and I don't plan to use it, so i'm not going to do that, but I don't have a problem if someone does that 😄

**Comment by BrunnerLivio** [comment]
Alright, maybe I'll figure something out. Will let you know when I'm finished.

**Comment by BrunnerLivio** [comment]
[Pull request is online](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15032). Even if you don't know TypeScript, maybe have a look over index.d.ts file, if it is correct. I think you'll understand it more or less. 

I added typings for methods on VanillaTilt class, which i considered as "public". Am I missing any?

```
static init(elements: HTMLElement | HTMLElement[], settings?: VanillaTilt.TiltOptions): void;
reset(): void;
getValues(): VanillaTilt.TiltValues;
destroy(): void;
addEventListeners(): void;
removeEventListener(): void;
```

**Comment by BrunnerLivio** [comment]
I got merged!

Now you can install typings using `npm install --save-dev @types/vanilla-tilt` 


![Fancy Preview](http://i.imgur.com/pJCaAnm.gif)

**Comment by micku7zu** [comment]
Merged the request. Thanks! :+1:
