### ISSUE TITLE
Object doesn't support this action - on IE 11

### ISSUE THREAD

**Issue by MarcoMedrano** [micku7zu/vanilla-tilt.js#17]
On branch https://github.com/bastilimbach/vanilla-tilt.js#fix/issue-15  this is working perfectly on IE11 but throws an annoying message on console:
`Object doesn't support this action`

`Line: this.element.dispatchEvent(new CustomEvent("tiltChange", {`

**Comment by micku7zu** [comment]
It seems that IE 9 / 10 / 11 have some problem with "new CustomEvent" ... can you please try with this [](https://github.com/krambuhl/custom-event-polyfill) ?

**Comment by MarcoMedrano** [comment]
Cool that worked! after npm I just included this line to use it.
`import 'custom-event-polyfill';`

Thanks!!
