### ISSUE TITLE
_vanillaTilt2.default.init is not a function ?

### ISSUE THREAD

**Issue by jesperlandberg** [micku7zu/vanilla-tilt.js#19]
Hi,

Thanks for the plugin, great to not need jQuery dependency.

I have an issue tho.

I get the error "_vanillaTilt2.default.init is not a function" when trying to init.

This is how I do it:

```
import VanillaTilt from 'vanilla-tilt'

const vanillaTilt = VanillaTilt.init(inner, {
  max: 7,
  speed: 2000
})
```

**Comment by BrunnerLivio** [comment]
Still does not work? Already discussed this in #15 

@bastilimbach should have fixed this already. Did you publish the latest version @micku7zu ?

**Comment by jesperlandberg** [comment]
@BrunnerLivio I npm installed it and the package.json says 1.3.0

**Comment by bastilimbach** [comment]
This is fixed by me in PR #16. I think @micku7zu forget to publish this version to npm. But to be honest I don't know if you need to publish it. I though this would get updated automatically. Maybe it doesn't update because we didn't change the version number in `package.json`?

**Comment by bastilimbach** [comment]
@jesperlandberg I deleted my fork so you need to wait for @micku7zu to look into this. Sorry

**Comment by BrunnerLivio** [comment]
> I though this would get updated automatically.

@bastilimbach

You need to publish it manually, after updating package.json version. [See here](https://docs.npmjs.com/getting-started/publishing-npm-packages#updating-the-package)

Could you do this @micku7zu ?

**Comment by bastilimbach** [comment]
> You need to publish it manually, after updating package.json version. See here

Oh, ok. Then this is probably the issue here 👍

**Comment by micku7zu** [comment]
I'm here, what do I need to do guys?

**Comment by micku7zu** [comment]
Done 👍 

Does it work now?

**Comment by jesperlandberg** [comment]
@micku7zu yup, thanks a lot=)

That was the last touch on my new site, jesperlandberg.com =)

**Comment by bastilimbach** [comment]
@jesperlandberg Sweet website. I found an issue but you didn't open source the website so I couldn't look into the code 😭 The link points alway to the vouge project. Also the `Drop me a line` button alway redirect to the cloudflare security page. After a refresh it works. But if you go through the Profile link, the `Drop me a line` link always points to cloudflare

**Comment by jesperlandberg** [comment]
@bastilimbach thanks for noticing, will fix=)

**Comment by BrunnerLivio** [comment]
@jesperlandberg glad we could help. Awesome website! Do you consider making it open source? I would love to see the code :)

**Comment by jesperlandberg** [comment]
@BrunnerLivio Sure, will repo it tomorow, just gotta better up on some code=)
