### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by soenkekluth** [micku7zu/vanilla-tilt.js#2]
my PR allows you to publish by executing one of the realease scripts.

the PR: https://github.com/micku7zu/vanilla-tilt.js/pull/1

**Comment by micku7zu** [comment]
Hi and thanks for this. That's why I renamed the project from vanillaTilt.js to **vanilla-tilt.js** so I can publish it to NPM under the same name 😄.

I was already working on this, but I will check your work and will accept the PR if everything is ok. 👍 

I'm new to all this "public open source project" amd PR / Issues. I hope I do it right

**Comment by micku7zu** [comment]
I merged the PR, whats the next move?

**Comment by BrunnerLivio** [comment]
Looking through your package.json, it looks like its ready to publish.

Here's a [tutorial](https://docs.npmjs.com/getting-started/publishing-npm-packages) how to publish it on npm, if you don't know it yet.

**Comment by micku7zu** [comment]
I didn't have enough time to check all this CommonJS and Webpack. I don't have enough knowledge about them, so, anyone who can help is welcome 😄

**Comment by BrunnerLivio** [comment]
@micku7zu I figured it out why this error happened. See Issue #11 
So now could you publish the package on npm? Or is it already?

**Comment by micku7zu** [comment]
@BrunnerLivio I will have a look on this later today :+1:

**Comment by micku7zu** [comment]
I can't run "npm run build" or anything... I don't have enough time to debug :(

**Comment by bastilimbach** [comment]
@micku7zu I fixed the build and deploy scripts. The "npm" before "run" was missing. But I still have the same issue as @BrunnerLivio. Will look into that now. 👍

**Comment by micku7zu** [comment]
Thanks @bastilimbach

**Comment by bastilimbach** [comment]
Ok, I got it. I think 😂. 
Will create a PR.

**Comment by bastilimbach** [comment]
Is it correct, that you use vanilla-tilt.bable.js in a script tag or CDN? That's the "not ES6 or whatever" version, right?

**Comment by bastilimbach** [comment]
Ok PR #12 should fix this error. 👍

**Comment by micku7zu** [comment]
Finally, it's here: https://www.npmjs.com/package/vanilla-tilt

Can you please check that everything it's ok and it's working fine? 😄 

Thanks @bastilimbach @BrunnerLivio

**Comment by BrunnerLivio** [comment]
Tried it with webpack and babel. Worked with using `require('vanilla-tilt');`! Good work everyone. 

Did not try using script-tag. Maybe need some feedback there before closing this issue

**Comment by bastilimbach** [comment]
I tested the script-tag with my implementation of the module wrapper. This worked perfectly. But as @micku7zu wrote in PR [#12 (Comment)](https://github.com/micku7zu/vanilla-tilt.js/pull/12#issuecomment-282146209) he isn't sure if the wrapper is the final/best solution.

**Comment by micku7zu** [comment]
Thanks guys, I close this issue and we will see about the module wrapper in the weekend :smile: I think will merge that too :+1: 

I will also have a look at bower :+1:

**Comment by bastilimbach** [comment]
Bower? That so 2015! 😂 Keep up the great work. 👍

**Comment by BrunnerLivio** [comment]
@bastilimbach True that haha, but I think in some use cases it is still usefull! Should not consume too much time to support it, so lets do it.

**Comment by micku7zu** [comment]
Oh god, I'm not good with all these package managers :joy:

**Comment by bastilimbach** [comment]
@micku7zu If you need help, open a WIP Pull Request 😉

**Comment by micku7zu** [comment]
I need an example of how do you use vanilla-tils.js using npm. Whats the flow?

**Comment by bastilimbach** [comment]
Well, you use it like the client side. Just write your normal: 
```javascript
.init(document.querySelector(".your-element"), {
		max: 25,
		speed: 400
	});
```
The `require` just makes it possible for module bundlers like Webpack to bundle vanilla-tilt with every other .js file into a big `bundle.js`. So what webpack does is, it collects all your modules/files look which methods you are using/are needed and extracts them. Then it bundles all these functions into one big `bundle.js` file, which is included via the script tag. Of course Webpack does a lot other cool stuff in the background, but that's the basic concept.
