### ISSUE TITLE
error on destroy() - .style of null

### ISSUE THREAD

**Issue by purepear** [micku7zu/vanilla-tilt.js#29]
I believe adding `clearTimeout(this.transitionTimeout);` in destroy method should fix the problem.
Right now i have no time for pull request :(

**Comment by micku7zu** [comment]
Fixing it today, thanks for the catch!

**Comment by purepear** [comment]
and also have to clean requestAnimationFrame
```
if (this.updateCall !== null) {
  cancelAnimationFrame(this.updateCall);
}
```

**Comment by micku7zu** [comment]
I have to do this, I hope this weekend

**Comment by micku7zu** [comment]
Done. Thanks!
