### ISSUE TITLE
Cant add glare effect

### ISSUE THREAD

**Issue by Bobeta** [micku7zu/vanilla-tilt.js#35]
It works great with React, thanks for your great work! The only thing I can't seem to get to work is adding glare effect to it, my current config looks like this:

```
      glare: 'true',
      'max-glare': 0.8,
      'glare-prerender': false,
```

What am I missing?

**Comment by BrunnerLivio** [comment]
Change `glare: 'true',` to `glare: true,` maybe?

**Comment by Bobeta** [comment]
@BrunnerLivio Thanks for the quick reply! I did that already but still the same

**Comment by BrunnerLivio** [comment]
@Bobeta in my example with React@16 it works:
https://codepen.io/BrunnerLivio/full/wEWmoN

Maybe the problem is somewhere else..?

**Comment by McToluene** [comment]
Please do you've a typescript example?

**Comment by BrunnerLivio** [comment]
@McToluene should not make any difference in regards of VanillaTilt?

**Comment by micku7zu** [comment]
It seems that this issue was answered by @BrunnerLivio. Thanks!
