### ISSUE TITLE
Parallax effect inner elements do not reset properly after activate

### ISSUE THREAD

**Issue by xtai** [micku7zu/vanilla-tilt.js#38]
![tilt](https://user-images.githubusercontent.com/3366724/47331681-c2846c00-d631-11e8-8597-a71e530ccdfb.png)

As shown in the screenshot, the inner elements will not reset themselves to pervious position after mouse hovering.

Issue replicated in Chrome 70 and FireFox 62.

The [jQuery version](http://gijsroge.github.io/tilt.js/) doesn’t have this issue.

**Comment by swashata** [comment]
I came across this too. One ugly solution is to add the css prop on hover

```css
.my-tiltable-element:hover {
  transform-style: preserve-3d;
```

**Comment by micku7zu** [comment]
Good catch. I updated the documentation: https://github.com/micku7zu/vanilla-tilt.js/commit/744a7de3d47fd4a84d5177f41e3c82ab272d8a4e. You can see here: https://micku7zu.github.io/vanilla-tilt.js/index.html

@swashata that is correct too, but it has a different output.
