### ISSUE TITLE
Is it really necessary to expose class to window?

### ISSUE THREAD

**Issue by swashata** [micku7zu/vanilla-tilt.js#40]
First of all thank you very much for this awesome library. It is really smooth and very performant.

Now for the question

https://github.com/micku7zu/vanilla-tilt.js/blob/26c648d8d9808ad0cba553a12f6fe530d5f4c830/lib/vanilla-tilt.es2015.js#L351-L359

I am using module bundler (webpack) and I am not used to exposing things to global `window`. I understand that `VanillaTilt` tries to init for all `[data-tilt]`, but is it really necessary to expose to a `window.VanillaTilt` variable? If we don't do that what could be the repurcussion?

If you think this isn't necessary then I can send you a PR for the change.

**Comment by BrunnerLivio** [comment]
Maybe `(window || global || {}).VanillaTilt = VanillaTilt` would fix this ? So this would not be a breaking change?

**Comment by swashata** [comment]
Or maybe perhaps an explicit dist file?

```js
import VanillaTilt from 'vanilla-tilt/lib/vanilla-tilt.module.js';
```

This module will not have any side-effects. So no expose to global or auto init `[data-tilt]`.

What say?

**Comment by micku7zu** [comment]
I'm not up to date with all the new gimmicks like Webpack, Babel, and all the others way frontend is done in 2018. If you find a way to not break what I've already done and solve your problem too, do a pull request  with what you need 😄
