### ISSUE TITLE
[docs] Mention NodeList is also supported

### ISSUE THREAD

**Issue by itaditya** [micku7zu/vanilla-tilt.js#42]
Currently in docs, the JS way of using the lib shows this code.

```js
VanillaTilt.init(document.querySelector(".your-element"), {
  max: 25,
  speed: 400
});
```

However it should be mentioned that we can also provide a NodeList via `document.querySelectorAll(".your-elements")`.

**Comment by micku7zu** [comment]
I updated the docs:
- https://github.com/micku7zu/vanilla-tilt.js/commit/f57ca7bcf4e9e8f3b29a93b839c56a63486c6067
- https://github.com/micku7zu/vanilla-tilt.js/commit/a6ddc4188f996e8b41bb506649d098da497f8edb
- https://github.com/micku7zu/vanilla-tilt.js/commit/002fb43a083f73dda90d0dfd28fcf07c4ecf42f0
Thanks!
