### ISSUE TITLE
IE Polyfill required

### ISSUE THREAD

**Issue by josias-r** [micku7zu/vanilla-tilt.js#49]
Since this library uses the [CustomEvent API](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent) it will throw an error on IE.
The following Polyfill works fine and should be included in the babel version:

https://polyfill.io/v3/polyfill.min.js?features=CustomEvent

**Comment by micku7zu** [comment]
It looks that the polyfill link provided doesn't work 😢, but I will include the polyfill from https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent. Thanks!

**Comment by josias-r** [comment]
I'm using the mentioned polyfill from [Polyfill.io](https://polyfill.io/v3/api/) in a browser and it works fine🤔, but I think the polyfill code won't show if the UA is unknown / supported.
The MDN polyfill should work just fine as well, thanks for working on this awesome library!

**Comment by micku7zu** [comment]
I wanted to implement this, but found out that this Polyfill is not included in Babel: https://github.com/zloirock/core-js/issues/354#issuecomment-350334898.

I will add a message on README. Thanks!

**Comment by micku7zu** [comment]
For anyone having this problem, please include the CustomEvent polyfill for Internet Explorer, before the vanilla-tilt.js:

```
(function () {

  if ( typeof window.CustomEvent === "function" ) return false;

  function CustomEvent ( event, params ) {
    params = params || { bubbles: false, cancelable: false, detail: null };
    var evt = document.createEvent( 'CustomEvent' );
    evt.initCustomEvent( event, params.bubbles, params.cancelable, params.detail );
    return evt;
   }

  CustomEvent.prototype = window.Event.prototype;

  window.CustomEvent = CustomEvent;
})();
```

Polyfill urls: 
- https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent
- https://polyfill.io/v3/polyfill.min.js?features=CustomEvent
- https://www.npmjs.com/package/custom-event-polyfill

**Comment by Imprasna** [comment]
(index):56 Uncaught ReferenceError: VanillaTilt is not defined 
I am getting this error can someone help me get this fixed, when using cdn I get this error in my console and it doesn't work the tilt functionality
