### ISSUE TITLE
Gyroscope problem

### ISSUE THREAD

**Issue by Asgarrrrr** [micku7zu/vanilla-tilt.js#52]
Hello, after many tests and tests, I allow myself to post here the fact that the use of the gyroscope does not seem to me any more possible. Impossible to make it work, as well on IOS as Android, Safari Chrome or Firefox ...

(Sorry, I'm french...)

**Comment by ktropp** [comment]
I am experiencing the same problem. You can test it on this site: http://owliss.kareltropp.cz/

On desktop everything works, on mobile nothing. 

It works on your example page: https://micku7zu.github.io/vanilla-tilt.js/ but not on my page. It is not a problem in my mobile device then.

**Comment by ktropp** [comment]
I figured out something. It works when using default android browser, but it doesn't work in Chrome.

**Comment by ktropp** [comment]
OMG, I figured it out. Your site needs https certificate for deviceorientation event to work. @Asgarrrrr test it and see if it works. I think we can close this issue.

**Comment by Asgarrrrr** [comment]
Hi ! Haha indeed it seems that this is the source of the problem, "https" is the sinequanone condition for it to work! I thank you @ktropp !

Sorry for the inconvenience.

**Comment by Enkirch** [comment]
Hi, why excactly do i need https for this? Is the phone not allowed to send the gyroscope informations without the ssl ?

**Comment by ktropp** [comment]
@Enkirch I don't know exactly, but it is a browser limitation, because you don't need SSL on some browsers.
