### ISSUE TITLE
Import into Vue.js project?

### ISSUE THREAD

**Issue by akinhwan** [micku7zu/vanilla-tilt.js#53]
Hello I'm having trouble with my vue.js project implementing this lib

I npm installed

in my component, i `import VanillaTilt from "vanilla-tilt";`
and add the necessary data attributes as shown in the example div

anything I'm missing?

**Comment by apodacaduron** [comment]
https://github.com/frogbob/vue-tilt.js

**Comment by henryz00** [comment]
For anyone who is still wondering, after adding `import VanillaTilt from "vanilla-tilt";`, just add 
```
VanillaTilt.init(this.$refs.refToDiv]);
```
in `mounted()` function, with your correct ref to the div item, it should work. See ['JS Way' section of the doc](https://micku7zu.github.io/vanilla-tilt.js/).

**Comment by mh-wanoon** [comment]
it's a plugin that allows you to work on the design of your page. so if anyone has already had the opportunity to integrate it on nuxt please help me do it. thank you

**Comment by mh-wanoon** [comment]
comments integrator vanilla-titl.js on nuxt.js
it's a plugin that allows you to work on the design of your page. so if anyone has already had the opportunity to integrate it on nuxt please help me do it. thank you
