### ISSUE TITLE
Disable Glare for set time

### ISSUE THREAD

**Issue by SethRzeszutek** [micku7zu/vanilla-tilt.js#55]
I have been attempting to disable the glare while the element flips. I tried changing opacity, however each time the mouse moves the element is updated. I have tried changing the attribute for glare to false through javascript but it doesn't update it.

**Comment by SethRzeszutek** [comment]
Made a fix on my end, I added another variable to the class called `this.glarePause = false` which would have no effect until I was able to mess with it in Javascript.

I then added a check for it:
`if (this.glare && !this.glarePause) {
      this.glareElement.style.transform = `rotate(${values.angle}deg) translate(-50%, -50%)`;
      this.glareElement.style.opacity = `${values.percentageY * this.settings["max-glare"] / 100}`;
    }'

Then I could manipulate it with a set time like:
`
destroyBox.vanillaTilt.glarePause = true;
setTimeout(function(){ destroyBox.vanillaTilt.glarePause = false }, 1000);
`

**Comment by micku7zu** [comment]
👍 I've wont add for the moment an option for that, who needs this can implement a custom solution.
