### ISSUE TITLE
IE Polyfill Issue

### ISSUE THREAD

**Issue by kolbykruger** [micku7zu/vanilla-tilt.js#61]
Hi all. I am having issues getting vanilla-tilt to work in IE. 

I have been referring to this post about using a custom event polyfill: https://github.com/micku7zu/vanilla-tilt.js/issues/49

However, I cannot seem to get this to work. It seems to do nothing, and it's described as a drop in solution that you include before the vanilla-tilt.js file.

I am using this polyfill - exactly as it is. Do I need to pass configs to it in any way?
```
(function () {

  if ( typeof window.CustomEvent === "function" ) return false;

  function CustomEvent ( event, params ) {
    params = params || { bubbles: false, cancelable: false, detail: null };
    var evt = document.createEvent( 'CustomEvent' );
    evt.initCustomEvent( event, params.bubbles, params.cancelable, params.detail );
    return evt;
   }

  CustomEvent.prototype = window.Event.prototype;

  window.CustomEvent = CustomEvent;
})();

//vanilla-tilt.js file included here...
```

Could anyone please explain what I need to do to get this working properly?

**Comment by kolbykruger** [comment]
For those wondering in the future, as I didn't entirely understand how polyfills work, you need to use the babel version of Vanilla Tilt for the above polyfill to work in IE.

Include the polyfill above, followed by the minified, or unminified script found here: https://cdnjs.cloudflare.com/ajax/libs/vanilla-tilt/1.7.0/vanilla-tilt.babel.min.js

**Comment by micku7zu** [comment]
Thanks! 👍
