### ISSUE TITLE
Disable on mobile

### ISSUE THREAD

**Issue by s5t5n** [micku7zu/vanilla-tilt.js#66]
How? I'm not a hardcoder. Can you provide a code to disable vanilla-tilt.js on device smaller than 768px?

**Comment by s5t5n** [comment]
Nevermind. Just've swithed of will-change to unset with @media

**Comment by terminal-guy** [comment]
> Nevermind. Just've swithed off will-change to unset with @media

I didn't understand I want to disable titlt.js in mobile devices can you help me?
