### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by micku7zu** [micku7zu/vanilla-tilt.js#7]
I think the dist/ files needs some CDN. Some simple solutions?

**Comment by posva** [comment]
You can use unpkg: http://unpkg.com/

**Comment by micku7zu** [comment]
Thanks, I will try after the package is in NPM 👍

**Comment by itaditya** [comment]
@micku7zu since you have hosted the project on Github Pages (that hosts static assets on its own CDN), we can simply use https://micku7zu.github.io/vanilla-tilt.js/src/vanilla-tilt.min.js as CDN link.

**Comment by itaditya** [comment]
Would be nice if the CDN is mentioned in docs. Really helpful for fiddling with libs like this on Codepen.
