### ISSUE TITLE
Glare sometimes results in mass distortion?

### ISSUE THREAD

**Issue by SumNeuron** [micku7zu/vanilla-tilt.js#70]
Sometimes glare works perfectly and I couldn't be happier. Sometimes it causes mass shearing and almost seizure inducing effects. How to get around?

**Comment by ishan-me** [comment]
I also faced this similar issue I am using Firefox and it causes some skew effect taking up the whole browser space for a second.

To see this excat issue you should open this inside of firefox i am using firefox developer edition looking at the documentation and hovering the tilt examples.

https://micku7zu.github.io/vanilla-tilt.js/

**Comment by micku7zu** [comment]
Thanks! I could replicate the issue in Firefox Developer edition last version, and fixed it here: https://github.com/micku7zu/vanilla-tilt.js/releases/tag/1.7.1

**Comment by ishan-me** [comment]
This indeed works. Thank you for your valuable library and contribution.
