### ISSUE TITLE
Flip to Backside

### ISSUE THREAD

**Issue by valentinwinkelmann** [micku7zu/vanilla-tilt.js#76]
Is there a way to rotate the element by 180 degrees? I would like to look at the back side. I was thinking of a container inside the element that I can rotate 180 degrees, but unfortunately the glare effect doesn't work.

I would like to display the whole thing animated, otherwise I could just change the content of the element for front and back, but important would be a real rotation as animation.

**Comment by micku7zu** [comment]
I didn't explore something like this, there is no functionality like this implemented in the library.
