### ISSUE TITLE
safari 14 macos

### ISSUE THREAD

**Issue by htlf** [micku7zu/vanilla-tilt.js#82]

**Comment by htlf** [comment]
On Safari14 macOS the effect works well but whatever is on top of the tilted div gets masked out.
Also it sets itself as the topmost element on the page with a strange see-through effect, regardless of any bkg color setting.
Not happening in Chrome. Not in Firefox. Not in Opera.

**Comment by micku7zu** [comment]
I'm sorry, I don't have any Safari/MacOS to debug this.

**Comment by htlf** [comment]
would you mind if i tried?

**Comment by micku7zu** [comment]
> would you mind if i tried?
> […](#)
> On 19 Apr 2021, at 10:33, Șandor Sergiu ***@***.***> wrote: ﻿ I'm sorry, I don't have any Safari/MacOS to debug this. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

You can try, and I accept pull requests if everything looks fine 😄

**Comment by micku7zu** [comment]
This is a bug in Safari: https://stackoverflow.com/questions/18146511/bug-in-css3-rotatey-transition-on-safari/18167565

You can fix it using `-webkit-transform: translateZ(1000px);` on the elements on top of the tilted div.

**Comment by nderambure** [comment]
The right value is -1000px, not 1000px ;)
