### ISSUE TITLE
Inconsistent animation speed

### ISSUE THREAD

**Issue by soni801** [micku7zu/vanilla-tilt.js#86]
## Description
The speed of the tilt animation in some instances is inconsistent, not linear.

## Example
Speed is inconsistent when hovering over cards in https://yessness.com/. ([source](https://github.com/soni801/yessness))
[Video](https://youtu.be/UQZv4AWEKjw).

## Expected behaviour
Consistent speed when hovering over elements, like the cards on [the preview website](https://micku7zu.github.io/vanilla-tilt.js/index.html).
[Video](https://youtu.be/zTG7pqwHmc8).

### Testing environment
**Tested on all major browsers.**
OS: Windows 10 Home version 20H2 (build 19042.985) x64
CPU: 12x Intel Core i7-8700 @ 3.20 GHz
GPU: Nvidia RTX 2070 8 GB (driver version 466.27)
RAM: 16 GB DDR4 2666 MHz

**Comment by micku7zu** [comment]
This effect is obtained by changing the CSS "transform" property. On your site you added the "transition" property "300ms ease" on all css properties (including transform), which means that you applied a transition to the property used to obtain the effect, which causes the bug.

You can remove "transition" completely or specify exactly on what properties you want the transition to be, with "transition-property: width, height, color" or what do you need.
