### ISSUE TITLE
Glare effect?

### ISSUE THREAD

**Issue by rma4ok** [micku7zu/vanilla-tilt.js#9]
Hello @micku7zu !
Is there any plans to implement a glare effect like in original one?

**Comment by micku7zu** [comment]
Sure, I will have a look, but I don't know exactly when 😄

**Comment by rma4ok** [comment]
Thank you! I know! Free time is luxury =)

**Comment by micku7zu** [comment]
I hope I will have a look this weekend 😄

**Comment by micku7zu** [comment]
Thanks to @BrunnerLivio the effect it is finally available.
