### ISSUE TITLE
How to reset the component?

### ISSUE THREAD

**Issue by 3GamersStudios** [micku7zu/vanilla-tilt.js#90]
I have a blazor WASM project and really like this library but, it only works when I reload the page, detailed in this stack post,
[The Post](https://stackoverflow.com/questions/68673047/how-to-correctly-inject-js-into-blazor?noredirect=1#comment121382866_68673047) 
How do I reset the component? 
thanks!

**Comment by micku7zu** [comment]
The library works in two ways:

- at loading time, when it is loaded on the page it will initialize all the DOM elements with attribute "data-tilt" on page (only elements that are on the page at that moment)
- or by using the VanillaTilt.init method from JS: `VanillaTilt.init(document.querySelectorAll("[data-tilt]"));` whenever you need to initialize the new elements on the page.

**Comment by 3GamersStudios** [comment]
Thanks that totally fixes the problem, the only other issue is that the glare box rotates faster then the element. Thus creating a weird effect. Did you already know about this bug?

**Comment by micku7zu** [comment]
Probably a misconfiguration. I can take a look if you can reproduce it somewhere online.

**Comment by 3GamersStudios** [comment]
It seems to happen randomly, so reproducing is hard,

**Comment by 3GamersStudios** [comment]
![image](https://user-images.githubusercontent.com/80543119/128618981-8181c272-f4b9-4805-84ec-4e0a7438879a.png)
This is the artifact that sometimes occurs.
