### ISSUE TITLE
Images wrapped in Picture ignore translateZ on Chrome & Firefox

### ISSUE THREAD

**Issue by gyoungbe** [micku7zu/vanilla-tilt.js#98]
Wrapping images in `<picture></picture>` causes tilt to ignore `transformZ()` on Chrome and Firefox. 

Renders correctly on Safari.

See [codepen example](https://codepen.io/gyoungbe/pen/abyEGMG).

**Comment by micku7zu** [comment]
This doesn't look to be an issue in vanilla-tilt.js at all, but a difference between Chrome/Firefox and Safari on how they render transform/translateZ in this specific use case.

I don't know also if Safari renders it correctly or not, I didn't study the HTMl/CSS specifications about translateZ in that depth to know which one renders it correctly.

Wrapping the images in `<div></div>` will have the same effect in Chrome (I don't have Safari to test how it works with div)

I think the `<picture>` HTML element does more than you think, and you need to study that. 
`<picture>` **It is not exactly a drop-in replacement for `<img>`** without changing anything else, you will have to adjust things to the new DOM structure. 

Replacing `<img>` with `<picture><img></picture>` will change the DOM structure and how it renders.

I've played a few minutes with your example, and adding `picture { display: contents; }` will make Chrome/Firefox to work the same as you described Safari. Maybe Safari have that by default? I'm not sure.

Also, another logical fix here is to put the style on <picture> not in <img>, I've tested that also and it works.

**Comment by gyoungbe** [comment]
@micku7zu Thank you, I was unable to find a solution other than removing `<picture>` in my use-case. I'll use your proposed solution.
