### ISSUE TITLE
Gyroscope Issue

### ISSUE THREAD

**Issue by ItsJonHowell** [micku7zu/vanilla-tilt.js#99]
I apologize if this is a silly question, but I'm still learning how to hack together things as I'm a designer and not a developer. Anyways, I've spent the last few days trying to figure out how to get the gyroscope to work. I was able to get the vanilla-tilt.js working on my site. However, I can't seem to figure out how to add the option for the gyroscope?

This is what I'm using right now:

```
<div id="#SomeID">
</div>
<script>
  document.addEventListener("DOMContentLoaded", (e)=> {
    VanillaTilt.init(document.querySelector("#SomeID"), {
		max: 4,
		speed: 100
	});  
  })
</script>
```

I've tried to add the following after "speed: 100" and it doesn't work?
```
  gyroscope: true,
  gyroscopeMinAngleX: -45,
  gyroscopeMaxAngleX: 45,
  gyroscopeMinAngleY: -45,
  gyroscopeMaxAngleY: 45,
```
  
  I really apologize if I'm doing something stupid here, but I'm just learning! Thanks in advance for your help and happy holidays.

**Comment by micku7zu** [comment]
The gyroscope feature is enabled in Vanilla-tilt.js by default, no need to configure anything. It works on Android but it looks like  iOS 13 turned gyroscope data off by default, it works only if the user gives permission: https://medium.com/flawless-app-stories/how-to-request-device-motion-and-orientation-permission-in-ios-13-74fc9d6cd140 

So, you need to request permission for gyroscope before initializing vanilla-tilt, which I'm not sure it is a good idea, to request gyroscope data only for a small UI effect.
